### ISSUE TITLE
How to include Chart.min.js

### ISSUE THREAD

**Issue by davidweinfls** [jorgemorgado/dashing-linechart#1]
Hi,

I'm following your instruction to download Chart.min.js and put it under app/assets/javascripts

However, my LineChart widget is showing nothing in my dashboard except its title. I'm suspecting the javascript dependency is not loaded properly.

Do you have any insights in this issue? Any suggestion helps. 

Thanks.

**Comment by jorgemorgado** [comment]
Howdy, You really just need to put the .js file in the assets/javascripts folder. All files with .js extension will be included. Did you check the access permissions on that file? Or SELinux in case you are enforcing it. Have a look at those and let me know. Regards.

**Comment by davidweinfls** [comment]
So I checked the read permission of my app/assets/javascripts/Chart.min.js and it looks good. 

Btw, I am using dashing-rails, https://github.com/gottfrois/dashing-rails, a rails-engine version of dashing. However, I was able to get other widgets, like sparkline, working without problems.

**Comment by jorgemorgado** [comment]
Uhm, that might be the issue. I haven't tested this widget on dashing-rails.. I don't know if dashing-rails automatically includes or how it includes the Javascript assets. The sparkline is a different story because it only uses assets that are already shipped with dashing (like rickshaw and d3). On the other hand the bar_chart, line_chart, and other *_chart widgets I've done require the http://www.chartjs.org/ library.

Here's another idea for you to test (although, I'm not sure if this is the best way): inside your `dashboards/` folder you should have a `layout.erb` template. Inside the `<head> ... </head>` section, try to add the following:

``` html
<script type="text/javascript" src="/assets/Chart.min.js"></script>
```

This way you force the client to load the library, even when it's not needed (thus this is kind of a sub-optimal solution). But maybe it works and then you need to check with dashing-rails.

**Comment by jorgemorgado** [comment]
Is this working for you now? Did you find the solution? And if yes, was there something you needed to change on this widget's code? Thanks for an update.

**Comment by jorgemorgado** [comment]
Since this is not a widget problem and there was not reply to my suggestions, I'm closing this issue.

**Comment by zicons** [comment]
I had the problem that my charts where not rendered on the dashboard.
Got the Javascript-Error: TypeError: (intermediate value).Pie is not a function

Realized that i was using Firefox, **then i tried Chromium  and it worked.**
